# Generated by Django 2.1.7 on 2019-05-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesor', models.CharField(default='Brak Informacji', max_length=200)),
                ('pamiec', models.CharField(default='Brak Informacji', max_length=200)),
                ('pamiec_ram', models.CharField(default='Brak Informacji', max_length=200)),
                ('bateria', models.CharField(default='Brak Informacji', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=200)),
                ('typ', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phoneBase.General'),
        ),
    ]
